spring:
  application:
    name: oauth-app-backend	
  datasource:
    url:
      jdbc:mysql://localhost:3306/auth_app
     username:root
     password:boot
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        formate_sql: true
        show_sql: true			
server:port: 8082

